import { FormattingRule } from "./smarts.js";
import { researchPapersRules } from "./pediatric_journal_rules/research_papers.js";

// This class is generated by AI

/** Class representing a paper type **/
export class PaperType {
    // 1. The name/ID of the paper type (e.g., "Research Article")
    public readonly name: string;
    
    // 2. A description of what this paper type is
    public readonly description: string;
    
    // 3. The essential element: the rules that apply to this type.
    public readonly rules: FormattingRule[]; 

    constructor(name: string, description: string, rules: FormattingRule[]) {
        this.name = name;
        this.description = description;
        this.rules = rules;
    }
}

/** List of paper types **/
export const paperTypes = [
    new PaperType("Research Article", "This is the most important type of article because it provides new information based on original research. A Research article is new because of the imaging findings in a disease or syndrome; it is new because of unique interventional processes; it is new because it expresses new manifestations or complications or follow-up of a disease or disorder. Research articles can be prospective or retrospective. They can be clinical or basic research. This type of article must not exceed 18 double–spaced typed pages excluding tables and pictures.", researchPapersRules),
    // TODO
];
